name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Compilar o TypeScript
        run: npm run build

      - name: Rodar testes com Jest
        run: npm test
